### ISSUE TITLE
Variation in results of various actions

### ISSUE THREAD

**Issue by gauraviiita** [Sirui-Xu/STARS#2]
Your work is adorable! I have a general question. In the results table, why does a single model result not outperform in all 15 cases of the H3.6M dataset or any other dataset? 
Here, your model outperforms most cases, but in some cases, the results of the previous approach are better than this model. What is the reason behind it?  
Also, in some actions, this model's results are far better than previous results, but in other actions, it is slightly better than the previous result. What is the reason for this? 
Your answer will be valuable to me
Thank you!

**Comment by Sirui-Xu** [comment]
Hi,

Thank you for your question. It is an interesting inquiry that warrants further exploration. The reasons might be as follows.

1. Cases in a dataset may have unique characteristics that pose different challenges for models. These challenges may include varying levels of complexity, data variations, or other factors. Our model, which has been improved with specific inductive biases such as temporal smoothness and spatial locality, may struggle with some cases while performing well in others that correspond to such inductive biases.
2. Our focus in this paper is on *diverse prediction*, and the primary improvement of our model is in this area. While the deterministic prediction model still outperforms the baseline by a small margin overall, the performance of the two models may differ in specific actions. This is because the overall performances on deterministic prediction are similar.
3. As discussed in #1 , in producing the deterministic prediction results in the tables of the supplementary material, we have discrepancies in the data preprocessing that could affect the results. We plan to update the table with the results of standard processing in the next version, following the literature on deterministic prediction.

I hope this answer provides some clarity. Please let me know if you have any further questions.

Best regards.
